-- MySQL Script generated by MySQL Workbench
-- Tue May 19 11:29:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema intmarket
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema intmarket
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `intmarket` ;
CREATE SCHEMA `intmarket` ;
USE `intmarket` ;

-- -----------------------------------------------------
-- Table `intmarket`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE `intmarket`.`utilisateur` (
  `idUtilisateur` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `prenom` VARCHAR(100) NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `mdp` VARCHAR(100) NOT NULL,
  `addresse` VARCHAR(100) NOT NULL,
  `panier` VARCHAR(250) NOT NULL,
  `role` VARCHAR(100) NULL,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intmarket`.`categorie`
-- -----------------------------------------------------
CREATE TABLE `intmarket`.`categorie` (
  `idCategorie` INT(11) NOT NULL AUTO_INCREMENT,
  `nomCategoriecol` VARCHAR(100) NOT NULL,
  `sousCategorie` int(11) ,
  PRIMARY KEY (`idCategorie`),
  FOREIGN KEY(`sousCategorie`) REFERENCES `intmarket`.`categorie` (`idCategorie`)
   )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intmarket`.`article`
-- -----------------------------------------------------
CREATE TABLE `intmarket`.`article` (
  `idArticle` INT(11) NOT NULL AUTO_INCREMENT,
  `nomArticle` VARCHAR(100) NOT NULL,
  `prixArticle` VARCHAR(100) NOT NULL,
  `imageArticle` VARCHAR(100) NOT NULL,
  `descriptionArticle` VARCHAR(100) NOT NULL,
  `quantite` INT NOT NULL,
  `categorie_idCategorie` INT(11),
  PRIMARY KEY (`idArticle`),
    FOREIGN KEY (`categorie_idCategorie`) REFERENCES `intmarket`.`categorie` (`idCategorie`)
   )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intmarket`.`commande`
-- -----------------------------------------------------
CREATE TABLE `intmarket`.`commande` (
  `idCommande` INT NOT NULL AUTO_INCREMENT,
  `dateCommande` DATE NOT NULL,
  `utilisateur_idUtilisateur` INT NOT NULL,
  `article_idArticle` INT NOT NULL,
  PRIMARY KEY (`idCommande`),
    FOREIGN KEY (`utilisateur_idUtilisateur`)
    REFERENCES `intmarket`.`utilisateur` (`idUtilisateur`),
    FOREIGN KEY (`article_idArticle`)
    REFERENCES `intmarket`.`article` (`idArticle`)
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intmarket`.`ligneCommande`
-- -----------------------------------------------------
CREATE TABLE `intmarket`.`ligneCommande` (
  `facture` DECIMAL(6,2) NOT NULL,
  `quantite` DECIMAL(3,0) NOT NULL,
  `commande_idCommande` INT NOT NULL,
  `article_idArticle` INT NOT NULL,
    FOREIGN KEY (`commande_idCommande`)
    REFERENCES `intmarket`.`commande` (`idCommande`),
    FOREIGN KEY (`article_idArticle`)
    REFERENCES `intmarket`.`article` (`idArticle`)
    )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
